/**
 * A deterministic (seeded, not random-per-run), realistic month of student
 * financial activity. Built regardless of whether the real inbox has
 * anything in it yet — the demo video must be able to run entirely on this
 * data (docs/BUILD-SPEC.md §6.4).
 *
 * Design choice: this module simulates raw (subject, sender, bodyText)
 * messages — exactly the same shape imap.ts hands to the shared pipeline —
 * rather than hand-building TransactionEvent objects directly. That means
 * the seeded month is generated by running through the SAME
 * heuristics -> (batched, opt-in) LLM fallback -> event pipeline that real
 * ingested email goes through (see pipeline.ts), so it genuinely exercises
 * that pipeline (including the review-queue and LLM-fallback code paths)
 * instead of being a pile of pre-categorized, already-clean data that never
 * touches the interesting logic. The only post-processing is relabeling
 * `source` to `'seed'` on the final events, so downstream code can always
 * tell seed data apart from anything real.
 */

import { processRawMessages, type ProcessRawMessagesOptions, type RawMessage } from './pipeline.js';
import { createSeededRandom, randInt } from './util.js';
import type { TransactionEvent } from './types.js';

export const DEFAULT_SEED = 42;

// A fixed calendar month (February 2026 — 28 days, so every day-of-month used
// below is guaranteed valid without special-casing month length).
const YEAR = 2026;
const MONTH_INDEX = 1; // 0-based: February

function dateAt(dayOfMonth: number, hour = 12): string {
  return new Date(Date.UTC(YEAR, MONTH_INDEX, dayOfMonth, hour, 0, 0)).toISOString();
}

function jitterCents(rand: () => number, baseCents: number, spreadCents: number): number {
  return baseCents + randInt(rand, -spreadCents, spreadCents);
}

function dollars(cents: number): string {
  return (cents / 100).toFixed(2);
}

/**
 * Generate the deterministic raw messages for one seeded student month.
 * Same `seed` always produces the same messages (same amounts, same order).
 */
export function generateRawMessages(seed: number = DEFAULT_SEED): RawMessage[] {
  const rand = createSeededRandom(seed);
  const messages: RawMessage[] = [];

  // ---------------------------------------------------------------------
  // Income: two biweekly paychecks, a financial aid disbursement, a clean
  // tutoring Venmo receipt, and a genuinely ambiguous Venmo "reimbursement".
  // ---------------------------------------------------------------------
  messages.push({
    subject: 'Account Alert',
    sender: 'alerts@chase.com',
    bodyText: `A $${dollars(jitterCents(rand, 41250, 500))} deposit was posted to your account ending in 4321 from PAYROLL`,
    timestamp: dateAt(3, 9),
  });
  messages.push({
    subject: 'Account Alert',
    sender: 'alerts@chase.com',
    bodyText: `A $${dollars(jitterCents(rand, 41250, 500))} deposit was posted to your account ending in 4321 from PAYROLL`,
    timestamp: dateAt(17, 9),
  });
  messages.push({
    subject: 'Account Alert',
    sender: 'alerts@chase.com',
    bodyText: `A $${dollars(180000)} deposit was posted to your account ending in 4321 from UMASS FINANCIAL AID DISBURSEMENT`,
    timestamp: dateAt(1, 8),
  });
  messages.push({
    subject: 'Alex Chen paid you',
    sender: 'venmo@venmo.com',
    bodyText: `Alex Chen paid you $40.00 for "calc tutoring"`,
    timestamp: dateAt(8, 15),
  });
  messages.push({
    subject: 'Jordan Kim paid you',
    sender: 'venmo@venmo.com',
    bodyText: `Jordan Kim paid you $18.00 for "ur half of costco lol"`,
    timestamp: dateAt(12, 19),
  });

  // ---------------------------------------------------------------------
  // Rent: a clean Venmo split, and the flagship ambiguous case from the
  // brief — a natural-language memo that is NOT an exact "rent" match.
  // ---------------------------------------------------------------------
  messages.push({
    subject: 'You paid Landlord Realty',
    sender: 'venmo@venmo.com',
    bodyText: `You paid $650.00 to Landlord Realty for "rent"`,
    timestamp: dateAt(2, 10),
  });
  messages.push({
    subject: 'You paid Steph Lee',
    sender: 'venmo@venmo.com',
    bodyText: `You paid $23.00 to Steph Lee for "🍕🍺 rent split lol"`,
    timestamp: dateAt(5, 21),
  });

  // Zelle, bank-hosted notification, no memo at all — another ambiguous case.
  messages.push({
    subject: 'Zelle payment sent',
    sender: 'alerts@chase.com',
    bodyText: `You sent $30.00 to Priya Patel via Zelle`,
    timestamp: dateAt(21, 16),
  });

  // ---------------------------------------------------------------------
  // Groceries (bank alerts, keyword-resolved locally — never LLM-eligible).
  // ---------------------------------------------------------------------
  const groceryStops: Array<[number, string]> = [
    [4, 'TRADER JOES'],
    [11, 'WHOLE FOODS'],
    [25, 'STOP SHOP'],
  ];
  for (const [day, store] of groceryStops) {
    messages.push({
      subject: 'Account Alert',
      sender: 'alerts@chase.com',
      bodyText: `A $${dollars(jitterCents(rand, 5500, 1500))} transaction was posted to your account ending in 4321 at ${store}`,
      timestamp: dateAt(day, 18),
    });
  }

  // ---------------------------------------------------------------------
  // DoorDash x4
  // ---------------------------------------------------------------------
  for (const day of [6, 10, 16, 22]) {
    messages.push({
      subject: 'Your DoorDash order receipt',
      sender: 'no-reply@doordash.com',
      bodyText: `Thanks for your order! Total: $${dollars(jitterCents(rand, 2300, 800))}`,
      timestamp: dateAt(day, 19),
    });
  }

  // ---------------------------------------------------------------------
  // Starbucks x6
  // ---------------------------------------------------------------------
  for (const day of [3, 7, 9, 14, 20, 27]) {
    messages.push({
      subject: 'Your Starbucks receipt',
      sender: 'receipts@starbucks.com',
      bodyText: `Thanks for visiting! Total: $${dollars(Math.max(jitterCents(rand, 650, 250), 200))}`,
      timestamp: dateAt(day, 8),
    });
  }

  // ---------------------------------------------------------------------
  // Subscriptions x2
  // ---------------------------------------------------------------------
  messages.push({
    subject: 'Account Alert',
    sender: 'alerts@chase.com',
    bodyText: `A $9.99 transaction was posted to your account ending in 4321 at SPOTIFY`,
    timestamp: dateAt(5, 6),
  });
  messages.push({
    subject: 'Account Alert',
    sender: 'alerts@chase.com',
    bodyText: `A $15.99 transaction was posted to your account ending in 4321 at NETFLIX`,
    timestamp: dateAt(5, 7),
  });

  // ---------------------------------------------------------------------
  // Amazon: one plain order, one textbook rental
  // ---------------------------------------------------------------------
  messages.push({
    subject: 'Your Amazon.com order confirmation',
    sender: 'order-update@amazon.com',
    bodyText: `Order Total: $34.99`,
    timestamp: dateAt(9, 13),
  });
  messages.push({
    subject: 'Your Amazon.com Textbook Rental order confirmation',
    sender: 'order-update@amazon.com',
    bodyText: `Order Total: $89.50`,
    timestamp: dateAt(2, 14),
  });

  // ---------------------------------------------------------------------
  // Uber rides x2, Uber Eats x1
  // ---------------------------------------------------------------------
  for (const day of [13, 19]) {
    messages.push({
      subject: 'Your Tuesday morning trip with Uber',
      sender: 'receipts@uber.com',
      bodyText: `Trip cost: $${dollars(jitterCents(rand, 1400, 500))}`,
      timestamp: dateAt(day, 9),
    });
  }
  messages.push({
    subject: 'Your Uber Eats order receipt',
    sender: 'receipts@uber.com',
    bodyText: `Total: $28.40`,
    timestamp: dateAt(18, 20),
  });

  // ---------------------------------------------------------------------
  // Target x2
  // ---------------------------------------------------------------------
  for (const day of [15, 24]) {
    messages.push({
      subject: 'Your Target order confirmation',
      sender: 'orders@target.com',
      bodyText: `Order Total: $${dollars(jitterCents(rand, 4200, 1200))}`,
      timestamp: dateAt(day, 12),
    });
  }

  // ---------------------------------------------------------------------
  // Utilities (bank alert)
  // ---------------------------------------------------------------------
  messages.push({
    subject: 'Account Alert',
    sender: 'alerts@chase.com',
    bodyText: `A $45.00 transaction was posted to your account ending in 4321 at XFINITY INTERNET`,
    timestamp: dateAt(6, 11),
  });

  // ---------------------------------------------------------------------
  // A PayPal purchase — resolved locally, never LLM-eligible.
  // ---------------------------------------------------------------------
  messages.push({
    subject: 'Receipt for your payment',
    sender: 'service@paypal.com',
    bodyText: `You sent $12.00 USD to Campus Print Shop`,
    timestamp: dateAt(23, 17),
  });

  return [...messages].sort((a, b) => (a.timestamp! < b.timestamp! ? -1 : a.timestamp! > b.timestamp! ? 1 : 0));
}

/**
 * Generate the full seeded month as TransactionEvents, running the raw
 * messages through the real ingest pipeline (heuristics + batched, opt-in
 * LLM fallback for ambiguous Venmo/Zelle memos). Final events are relabeled
 * `source: 'seed'` regardless of which pipeline stage actually resolved
 * them, so they can always be identified/purged as synthetic data.
 */
export async function generateSeedMonth(
  seed: number = DEFAULT_SEED,
  opts: ProcessRawMessagesOptions = {},
): Promise<TransactionEvent[]> {
  const messages = generateRawMessages(seed);
  const events = await processRawMessages(messages, opts);
  return events.map((event) => ({ ...event, source: 'seed' as const }));
}
